name: 📝 Make Build Check

on:
  push:
    branches: [main]
    paths:
      - 'Makefile'
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - 'Makefile'
      - 'src/**'
  workflow_dispatch:

jobs:
  run:
    name: 📝 Make Build Check
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4 # Upgraded to prevent v2 deprecation warnings

      - name: 🏃 Run Build and Format inside Amiga Container
        uses: docker://walkero/docker4amigavbcc:latest-m68k
        with:
          args: >
            sh -c "
            apt-get update && apt-get install -y clang-format &&
            make &&
            make format
            "

      - name: 🏃 Running format check on Host
        run: git diff --exit-code
